// Code generated by github.com/skycoin/skyencoder. DO NOT EDIT.
package skyencoder

import (
	"errors"
	"math"

	"github.com/skycoin/skycoin/src/cipher/encoder"
)

// EncodeSizeMaxLenNestedSliceStruct1 computes the size of an encoded object of type MaxLenNestedSliceStruct1
func EncodeSizeMaxLenNestedSliceStruct1(obj *MaxLenNestedSliceStruct1) int {
	i0 := 0

	// obj.Foo
	i0 += 4
	for _, x := range obj.Foo {
		i1 := 0

		// x.Foo
		i1 += 4 + len(x.Foo)

		i0 += i1
	}

	return i0
}

// EncodeMaxLenNestedSliceStruct1 encodes an object of type MaxLenNestedSliceStruct1 to the buffer in encoder.Encoder
func EncodeMaxLenNestedSliceStruct1(e *encoder.Encoder, obj *MaxLenNestedSliceStruct1) error {

	// obj.Foo length check
	if len(obj.Foo) > math.MaxUint32 {
		return errors.New("obj.Foo length exceeds math.MaxUint32")
	}

	// obj.Foo length
	e.Uint32(uint32(len(obj.Foo)))

	// obj.Foo
	for _, x := range obj.Foo {

		// x.Foo maxlen check
		if len(x.Foo) > 3 {
			return encoder.ErrMaxLenExceeded
		}

		// x.Foo length check
		if len(x.Foo) > math.MaxUint32 {
			return errors.New("x.Foo length exceeds math.MaxUint32")
		}

		// x.Foo
		e.ByteSlice([]byte(x.Foo))

	}

	return nil
}

// DecodeMaxLenNestedSliceStruct1 decodes an object of type MaxLenNestedSliceStruct1 from the buffer in encoder.Decoder
func DecodeMaxLenNestedSliceStruct1(d *encoder.Decoder, obj *MaxLenNestedSliceStruct1) error {
	{
		// obj.Foo

		ul, err := d.Uint32()
		if err != nil {
			return err
		}

		length := int(ul)
		if length < 0 || length > len(d.Buffer) {
			return encoder.ErrBufferUnderflow
		}

		if length != 0 {
			obj.Foo = make([]MaxLenStringStruct1, length)

			for z1 := range obj.Foo {
				{
					// obj.Foo[z1].Foo

					ul, err := d.Uint32()
					if err != nil {
						return err
					}

					length := int(ul)
					if length < 0 || length > len(d.Buffer) {
						return encoder.ErrBufferUnderflow
					}

					if length > 3 {
						return encoder.ErrMaxLenExceeded
					}

					obj.Foo[z1].Foo = string(d.Buffer[:length])
					d.Buffer = d.Buffer[length:]
				}
			}
		}
	}

	if len(d.Buffer) != 0 {
		return encoder.ErrRemainingBytes
	}

	return nil
}
